apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.name }}